# Generated by Django 4.1.7 on 2023-02-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_watchlist', '0002_streamplatforms_watchlist_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatforms',
            old_name='webssite',
            new_name='website',
        ),
    ]
