# Generated by Django 4.1.7 on 2023-02-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_watchlist', '0003_rename_webssite_streamplatforms_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='app_watchlist.streamplatforms'),
            preserve_default=False,
        ),
    ]
